"""campos de verificacion

Revision ID: 9bdf99b0ba78
Revises: 1afb1ccb8463
Create Date: 2026-02-05 20:22:20.184861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bdf99b0ba78'
down_revision = '1afb1ccb8463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verificado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('codigo_verificacion', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('codigo_expiracion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('codigo_expiracion')
        batch_op.drop_column('codigo_verificacion')
        batch_op.drop_column('verificado')

    # ### end Alembic commands ###
